import '@/styles/globals.css'
import { useLocale } from 'next-intl'
import { Inter } from 'next/font/google'

import Analytics from '@/components/misc/Analytics'
import Footer from '@/components/layout/Footer'
import Header from '@/components/layout/Header'
import { LOCALES_TYPE } from '@/utils/constants'
import Providers from './providers'

const inter = Inter({ subsets: ['latin'] })

if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
	throw new Error('Missing Supabase ENV variables')
}

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

// export const generateStaticParams = () => LOCALES.langs.map((lang) => ({ lang }))

const RootLayout = ({
	children,
}: {
	children: React.ReactNode
}) => {
	const locale = useLocale() as LOCALES_TYPE
	return (
		<html lang={locale} className={inter.className}>
			<head />
			<Analytics />
			<body className="flex flex-col items-center justify-between min-h-screen p-12 bg-slate-50/40 dark:bg-zinc-800">
				<Providers>
					<header className="flex w-full px-4 backdrop-blur bh-zinc-900/50">
						<Header lang={locale} />
					</header>
					<main className="flex flex-col w-full gap-8 my-8 md:gap-16 md:my-14 lg:my-20">
						{children}
					</main>
					<footer className="flex border-t inset-2x-0 border-zinc-500/10 dark:border-zinc-200">
						<Footer />
					</footer>
				</Providers>
			</body>
		</html>
	)
}
export default RootLayout
